
Head:
  Activate: True
  Dimension:
    x:  60
    y:  60
    z:  200
  CurrPos:
    x:  250
    y:  100
    z:  0 

Eye:
  Activate: True
  Dimension:
    x:  100
    y:  100
    z:  50
  CurrPos:
    x:  200
    y:  200
    z:  450
    
MegaEye:
  Activate: True
  Dimension:
    x:  100
    y:  100
    z:  50
  CurrPos:
    x:  100
    y:  100
    z:  450

LeftLeg:
  Activate: True
  Dimension:
    x:  150
    y:  150
    z:  50
  CurrPos:
    x:  100
    y:  100
    z:  700 

RightLeg:
  Activate: True
  Dimension:
    x:  100
    y:  100
    z:  70 
  CurrPos:
    x:  500
    y:  100
    z:  700 